### ISSUE TITLE
‘dironly.m’ is missing

### ISSUE THREAD

**Issue by qvzhipeng** [Coastal-Imaging-Research-Network/runupTool-Toolbox#3]
Hello, Birchler. I find a file named ‘dironly.m’ is missing when I run demo_runupTool.m. It will be a huge help to me if you can share the missing program. 
Looking forward to your reply.
Thank you so much.
My email：quzhipeng@stu.ouc.edu.cn

**Comment by amrutharajv005** [comment]
please provide 'dironly.m' file. I am not able to process further due to the missing file. 

My email Id: amrutha9605@gmail.com
ThankYou.

**Comment by RobinMorrisLuo** [comment]
Hello. I find a file named ‘dironly.m’ is missing when I run demo_runupTool.m. It will be a huge help to me if you can share the missing program.
Looking forward to your reply.
Thank you so much.
My email：1633713186@qq.com

**Comment by eswanson-usgs** [comment]
This issue was resolved with commit 307c8cb
